version: "3.7"

services:

  cfssl:
    command:
      - bash
      - -c
      - |
          set -euxo pipefail
          [ -f cert/server.pem -a -f key/server-key.pem ] && exit
          # cfssl print-defaults config > conf/ca-config.json
          # cfssl print-defaults csr > conf/ca-csr.json
          cfssl gencert -initca conf/ca-csr.json | cfssljson -bare ca
          cfssl gencert -ca=ca.pem -ca-key=ca-key.pem --config=conf/ca-config.json -profile=server conf/server-csr.json | cfssljson -bare server
          mv server.pem cert
          mv server-key.pem key
    entrypoint: []
    image: cfssl/cfssl:${CFSSL_IMAGE_TAG}
    volumes:
      - ./cfssl-conf:/tmp/conf:ro
      - nginx_cert:/tmp/cert
      - nginx_key:/tmp/key
    working_dir: /tmp

  guacamole:
    command:
      - sh
      - -c
      - |
          set -eux
          /opt/guacamole/bin/initdb.sh --postgres > initdb.sql
    image: guacamole/guacamole:${GUACAMOLE_IMAGE_TAG}
    volumes:
      - postgres_initdb:/docker-entrypoint-initdb.d
    working_dir: /docker-entrypoint-initdb.d

volumes:
  nginx_cert:
  nginx_key:
  postgres_initdb:
