version: "3.7"

services:

  guacamole:
    command:
      - sh
      - -c
      - |
          set -eux
          /opt/guacamole/bin/initdb.sh --postgres > initdb.sql
    image: guacamole/guacamole:${GUACAMOLE_IMAGE_TAG}
    volumes:
      - "${POSTGRES_INITDB_HOST_DIR}:/docker-entrypoint-initdb.d"
    working_dir: /docker-entrypoint-initdb.d

volumes:
  postgres_initdb: