version: "3.7"

services:

  adminer:
    depends_on:
      - postgres
    image: adminer:${ADMINER_IMAGE_TAG}
    restart: unless-stopped

  cadvisor:
    command:
      - -url_base_prefix=/cadvisor
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=https://localhost:${NGINX_HOST_PORT}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    image: grafana/grafana:${GRAFANA_IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./grafana-examples:/mnt/examples:ro
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - grafana_data:/var/lib/grafana

  guacd:
    environment:
      - GUACD_LOG_LEVEL
    hostname: guacd
    image: guacamole/guacd:${GUACD_IMAGE_TAG}
    restart: unless-stopped

  guacamole:
    depends_on:
      - guacd
      - postgres
    environment:
      - GUACAMOLE_HOME=/etc/guacamole
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    hostname: guacamole
    image: guacamole/guacamole:${GUACAMOLE_IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - guacamole_conf:/etc/guacamole

  nginx:
    depends_on:
      - adminer
      - cadvisor
      - grafana
      - guacamole
      - node_exporter
      - prometheus
    extra_hosts:
      - node_exporter:${NODE_EXPORTER_HOST}
    image: nginx:${NGINX_IMAGE_TAG}
    restart: unless-stopped
    ports:
      - ${NGINX_HOST_PORT}:443
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - nginx_cert:/etc/ssl/certs/nginx:ro
      - nginx_key:/etc/ssl/private/nginx:ro

  node_exporter:
    image: quay.io/prometheus/node-exporter:${NODE_EXPORTER_IMAGE_TAG}
    container_name: node_exporter
    command:
      - --path.rootfs=/host
      - --web.telemetry-path=/node-exporter/metrics
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

  postgres:
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_initdb:/docker-entrypoint-initdb.d

  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=/prometheus/
    depends_on:
      - cadvisor
      - node_exporter
    extra_hosts:
      - node_exporter:${NODE_EXPORTER_HOST}
    image: prom/prometheus:${PROMETHEUS_IMAGE_TAG}
    restart: unless-stopped    
    volumes:
      - ./prometheus-conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

volumes:
  grafana_data:
  grafana_log:
  guacamole_conf:
  nginx_cert:
  nginx_key:
  postgres_data:
  postgres_initdb:
  prometheus_data:
