version: "3.7"

services:

  adminer:
    depends_on:
    - postgres
    image: adminer:${ADMINER_IMAGE_TAG}
    ports:
      - "8081:8080"
    restart: unless-stopped

  guacd:
    environment:
    - GUACD_LOG_LEVEL
    hostname: guacd
    image: guacamole/guacd:${GUACD_IMAGE_TAG}
    restart: unless-stopped

  guacamole:
    depends_on:
    - guacd
    - postgres
    environment:
    - GUACAMOLE_HOME=/etc/guacamole
    - GUACD_HOSTNAME
    - GUACD_PORT
    - POSTGRES_HOSTNAME
    - POSTGRES_PORT
    - POSTGRES_DATABASE=${POSTGRES_DB}
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    hostname: guacamole
    image: guacamole/guacamole:${GUACAMOLE_IMAGE_TAG}
    ports:
    - "8080:8080"
    restart: unless-stopped
    volumes:
      - "guacamole_conf:/etc/guacamole"

  # nginx:
  #   image: nginx:${NGINX_IMAGE_TAG}
  #   restart: unless-stopped
  #   # ports:
  #   # - "${NGINX_HOST_PORT}:80"

  postgres:
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: unless-stopped
    user: postgres
    volumes:
      - "${POSTGRES_DATA_HOST_DIR}:/var/lib/postgresql/data"
      - "${POSTGRES_INITDB_HOST_DIR}:/docker-entrypoint-initdb.d"

volumes:
  guacamole_conf:
  postgres_data:
  postgres_initdb:
