global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 60s
alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets: []
scrape_configs:
  - job_name: cadvisor
    metrics_path: /cadvisor/metrics
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node
    metrics_path: /node-exporter/metrics
    static_configs:
      - targets:
          - node_exporter:9100
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: /prometheus/metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - prometheus:9090