{
 "title": "Container",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Name",
    "query": {
     "query": "query_result(count(container_start_time_seconds) by (name))"
    }
   }
  ]
 },
 "panels": [
  { "title": "${container_name}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "container_name" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{name=~\"$container_name\"}[2m]))",
     "legendFormat": "now"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{name=~\"$container_name\"}[$__range]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{name=~\"$container_name\"})",
     "legendFormat": "now"
    },
    {
     "expr": "max(avg_over_time(container_memory_usage_bytes{name=~\"$container_name\"}[$__range]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "max(irate(container_network_transmit_bytes_total{name=~\"$container_name\"}[2m]))",
     "legendFormat": "out - now"
    },
    {
     "expr": "max(rate(container_network_transmit_bytes_total{name=~\"$container_name\"}[$__range]))",
     "legendFormat": "out - all"
    },
    {
     "expr": "-1 * max(rate(container_network_receive_bytes_total{name=~\"$container_name\"}[2m]))",
     "legendFormat": "in - now"
    },
    {
     "expr": "-1 * max(rate(container_network_receive_bytes_total{name=~\"$container_name\"}[$__range]))",
     "legendFormat": "in -all"
    }
   ]
  }
 ]
}