{
 "title": "Node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "network_device",
    "label": "Network Device",
    "query": {
     "query": "query_result(count(node_network_device_id) by (device))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "now" },
    {
     "expr": "avg_over_time(node_load1[$__range])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg by (cpu) (irate(node_cpu_seconds_total{mode!=\"idle\"}[2m])))",
     "legendFormat": "now"
    },
    {
     "expr": "sum(avg by (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[$__range])))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "now"
    },
    {
     "expr": "avg_over_time(node_memory_MemTotal_bytes[$__range]) - avg_over_time(node_memory_MemAvailable_bytes[$__range])",
     "legendFormat": "all"
    }
   ]
  },
  { "title": "Network Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$network_device",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "repeat": "network_device",
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"$network_device\"}[2m])",
     "legendFormat": "out - now"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$network_device\"}[$__range])",
     "legendFormat": "out - all"
    },
    {
     "expr": "-1 * irate(node_network_receive_bytes_total{device=~\"$network_device\"}[2m])",
     "legendFormat": "in - now"
    },
    {
     "expr": "-1 * rate(node_network_receive_bytes_total{device=~\"$network_device\"}[$__range])",
     "legendFormat": "in - all"
    }
   ]
  }
 ]
}